### ISSUE TITLE
Support PHP 5

### ISSUE THREAD

**Issue by oToToT** [splitline/PHPFuck#1]
I think that this only works in PHP 7 QAQ.

**Comment by splitline** [comment]
cool
i only test on my php7 :/

---

I can't figure out why
```php
var_dump( (([]^[]).[])[0] );
```
failed on php5

but
```php
$x=(([]^[]).[]);
var_dump( $x[0] );
```
 will work.

I guess that it's AST parse wrongly

PHP SUCKS = =

**Comment by splitline** [comment]
Ok I got it

PHP 5 doesn't support things like this
```php
'abc'[1]
```
and this is the main idea to make this obfuscator.

So, **wontfix** :)


close 8888888

**Comment by oToToT** [comment]
It's quite sad. QAQ...
Btw, maybe you could notify users about the version this project supports in README.
